export const MOCK_ECOLE = {
  id: 'e1',
  name: 'École des Arts de Reims',
  type: 'École supérieure privée',
  uai: '0511234A',
  address: 'Rue des Arts, 51100 Reims',
  phone: '+33 3 26 XX XX XX',
  website: 'ecole-arts-reims.fr',
  description:
    "École supérieure d'arts plastiques et design au cœur de Reims. Formations en arts, design graphique et photographie. 145 étudiants, 12 enseignants.",
  founded: '2005',
  studentCount: 145,
  teacherCount: 12,
  diplomaCount: 89,
  coverUrl: 'https://images.pexels.com/photos/1266808/pexels-photo-1266808.jpeg?w=800',
  avatarColor: '#DC2626',
  initials: 'EA',
  verified: true,
  accreditation: 'Titre RNCP Niveau 6',
  insertionRate: 87,
} as const;

export const MOCK_FORMATIONS = [
  {
    id: 'f1',
    title: 'Design Graphique & Identité Visuelle',
    level: 'Bac+3',
    duration: '3 ans',
    capacity: 25,
    enrolled: 22,
    description: 'Formation complète en design graphique, branding et communication visuelle.',
    imageUrl: 'https://images.pexels.com/photos/196644/pexels-photo-196644.jpeg?w=400',
    price: '6 500€/an',
    diploma: 'Bachelor Design',
    tags: ['Design', 'Branding', 'Digital'],
    openForInscription: true,
  },
  {
    id: 'f2',
    title: 'Photographie Artistique & Commerciale',
    level: 'Bac+2',
    duration: '2 ans',
    capacity: 20,
    enrolled: 18,
    description: 'Maîtrisez la photographie sous toutes ses formes, du studio au reportage.',
    imageUrl: 'https://images.pexels.com/photos/3617500/pexels-photo-3617500.jpeg?w=400',
    price: '5 200€/an',
    diploma: 'BTS Photo',
    tags: ['Photo', 'Studio', 'Reportage'],
    openForInscription: true,
  },
  {
    id: 'f3',
    title: 'Arts Plastiques & Expression Contemporaine',
    level: 'Bac+4',
    duration: '4 ans',
    capacity: 15,
    enrolled: 15,
    description: "Explorez toutes les formes d'expression artistique contemporaine.",
    imageUrl: 'https://images.pexels.com/photos/1266808/pexels-photo-1266808.jpeg?w=400',
    price: '7 200€/an',
    diploma: 'Master Arts',
    tags: ['Peinture', 'Sculpture', 'Installation'],
    openForInscription: false,
  },
] as const;

export const MOCK_ECOLE_EVENTS = [
  {
    id: 'ev1',
    title: 'Journée Portes Ouvertes',
    date: 'Samedi 17 mai · 10h-17h',
    location: 'École des Arts',
    imageUrl: 'https://images.pexels.com/photos/1266808/pexels-photo-1266808.jpeg?w=600',
    attendees: 0,
    maxAttendees: 200,
    price: 'Gratuit',
    description: 'Venez découvrir nos formations, rencontrer nos enseignants et visiter nos ateliers.',
    type: 'portes_ouvertes',
  },
  {
    id: 'ev2',
    title: 'Vernissage Expositions Étudiantes',
    date: 'Vendredi 23 mai · 18h',
    location: "Galerie de l'École",
    imageUrl: 'https://images.pexels.com/photos/3617500/pexels-photo-3617500.jpeg?w=600',
    attendees: 45,
    maxAttendees: 100,
    price: 'Gratuit',
    description: 'Exposition des travaux des étudiants de 2ème et 3ème année.',
    type: 'exposition',
  },
  {
    id: 'ev3',
    title: 'Masterclass Photo avec Pro',
    date: 'Mercredi 28 mai · 14h',
    location: 'Studio Photo',
    attendees: 8,
    maxAttendees: 12,
    price: '30€',
    imageUrl: 'https://images.pexels.com/photos/3617500/pexels-photo-3617500.jpeg?w=600',
    description: 'Masterclass avec un photographe professionnel parisien.',
    type: 'masterclass',
  },
] as const;

export const MOCK_ALUMNI = [
  {
    id: 'al1',
    name: 'Julie Moreau',
    promo: '2022',
    job: 'Directrice Artistique',
    company: 'Agence Créa Paris',
    imageUrl: null,
    initials: 'JM',
    color: '#DC2626',
  },
  {
    id: 'al2',
    name: 'Marc Dubois',
    promo: '2021',
    job: 'Photographe Freelance',
    company: 'Auto-entrepreneur',
    imageUrl: null,
    initials: 'MD',
    color: '#DC2626',
  },
  {
    id: 'al3',
    name: 'Sophie Chen',
    promo: '2023',
    job: 'Designer UX/UI',
    company: 'Startup Reims Tech',
    imageUrl: null,
    initials: 'SC',
    color: '#DC2626',
  },
] as const;

export const MOCK_PARTNERS_ECOLE = [
  { id: 'p1', name: 'Agence 360 Reims', type: 'Stage & Emploi', logo: '🎨', color: '#7C3AED', since: '2022' },
  { id: 'p2', name: 'Belga Queen', type: 'Partenaire Photo', logo: '🍺', color: '#16A34A', since: '2024' },
  { id: 'p3', name: 'Ville de Reims', type: 'Soutien institutionnel', logo: '🏛️', color: '#2A2FFF', since: '2023' },
] as const;

export const MOCK_ECOLE_PUBLIC = {
  ...MOCK_ECOLE,
  photos: [
    'https://images.pexels.com/photos/1266808/pexels-photo-1266808.jpeg?w=400',
    'https://images.pexels.com/photos/196644/pexels-photo-196644.jpeg?w=400',
    'https://images.pexels.com/photos/3617500/pexels-photo-3617500.jpeg?w=400',
    'https://images.pexels.com/photos/1458457/pexels-photo-1458457.jpeg?w=400',
    'https://images.pexels.com/photos/1595385/pexels-photo-1595385.jpeg?w=400',
    'https://images.pexels.com/photos/2263436/pexels-photo-2263436.jpeg?w=400',
  ],
};

