export const PASSPORT_LEVELS = {
  basic: {
    id: 'basic',
    name: 'Basic',
    color: '#6B7280',
    gradient: ['#374151', '#1F2937'] as const,
    description: 'Débute ton aventure rémoise',
    minPoints: 0,
    maxPoints: 500,
    perks: ['Accès événements classiques', 'Premiers tampons', 'Participation aux tournées'],
  },
  silver: {
    id: 'silver',
    name: 'Silver',
    color: '#9CA3AF',
    gradient: ['#6B7280', '#374151'] as const,
    description: 'Tu connais Reims',
    minPoints: 500,
    maxPoints: 1500,
    perks: ['Événements exclusifs', 'Réductions partenaires', 'Coupe-file événements'],
  },
  gold: {
    id: 'gold',
    name: 'Gold',
    color: '#F59E0B',
    gradient: ['#D97706', '#92400E'] as const,
    description: 'Acteur incontournable',
    minPoints: 1500,
    maxPoints: 5000,
    perks: ['Accès VIP', 'Invitations privées maisons de champagne', 'Expériences uniques'],
  },
  neo: {
    id: 'neo',
    name: 'Néo-arrivant',
    color: '#2A2FFF',
    gradient: ['#2A2FFF', '#1A1ECC'] as const,
    description: 'Bienvenue à Reims !',
    minPoints: 0,
    maxPoints: 500,
    perks: ['Découverte de la ville', 'Avantages intégration', 'Rencontres facilitées'],
  },
  business: {
    id: 'business',
    name: 'Business',
    color: '#0D0F2E',
    gradient: ['#0D0F2E', '#1C1F4A'] as const,
    description: 'Réseau professionnel local',
    minPoints: 1000,
    maxPoints: 999999,
    perks: ['Réseau B2B local', 'Événements networking', 'Visibilité partenaires'],
  },
  press: {
    id: 'press',
    name: 'Press Yunicity',
    color: '#DC2626',
    gradient: ['#DC2626', '#991B1B'] as const,
    description: 'Créateur de contenu territorial',
    minPoints: 2000,
    maxPoints: 999999,
    perks: ['Badge certifié créateur', 'Publication articles premium', 'Programme rémunération'],
  },
} as const;

export type PassportLevelId = keyof typeof PASSPORT_LEVELS;

export const PASSPORT_LEVEL_ORDER: PassportLevelId[] = [
  'basic',
  'silver',
  'gold',
  'neo',
  'business',
  'press',
];

export const PERK_GROUP_ORDER: PassportLevelId[] = ['basic', 'silver', 'gold', 'business', 'press'];

export const MOCK_STAMPS = [
  {
    id: 'st1',
    partnerId: 'c2',
    partnerName: 'Belga Queen',
    emoji: '🍺',
    date: '12 avril 2026',
    address: "Place d'Erlon",
    obtained: true,
  },
  {
    id: 'st2',
    partnerId: 'c1',
    partnerName: 'Boulangerie du Marché',
    emoji: '🥐',
    date: '10 avril 2026',
    address: 'Place du Marché',
    obtained: true,
  },
  {
    id: 'st3',
    partnerId: 'a1',
    partnerName: 'Jazz au Parvis',
    emoji: '🎷',
    date: '8 avril 2026',
    address: 'Parvis Cathédrale',
    obtained: true,
  },
  {
    id: 'st4',
    partnerId: 'c4',
    partnerName: 'Ao Barber',
    emoji: '💈',
    date: null,
    address: 'Centre-ville',
    obtained: false,
  },
  {
    id: 'st5',
    partnerId: 'c5',
    partnerName: 'Cave des Sacres',
    emoji: '🍾',
    date: null,
    address: 'Rue de Mars',
    obtained: false,
  },
  {
    id: 'st6',
    partnerId: 'a2',
    partnerName: 'Cyclistes de Reims',
    emoji: '🚴',
    date: null,
    address: "Parc de la Patte d'Oie",
    obtained: false,
  },
] as const;

export type MockStamp = (typeof MOCK_STAMPS)[number];

export const MOCK_PERKS = [
  {
    id: 'pk1',
    partnerId: 'c2',
    partnerName: 'Belga Queen',
    offer: '1 verre offert à chaque visite',
    icon: '🍺',
    color: '#16A34A',
    level: 'basic',
    active: true,
  },
  {
    id: 'pk2',
    partnerId: 'c4',
    partnerName: 'Ao Barber',
    offer: 'Coupe offerte au 5ème passage',
    icon: '💈',
    color: '#0891B2',
    level: 'basic',
    active: true,
  },
  {
    id: 'pk3',
    partnerId: 'c5',
    partnerName: 'Cave des Sacres',
    offer: 'Bouteille de champagne à -20%',
    icon: '🍾',
    color: '#7C3AED',
    level: 'silver',
    active: false,
  },
  {
    id: 'pk4',
    partnerId: 'a1',
    partnerName: 'Jazz au Parvis',
    offer: 'Accès VIP soirées privées',
    icon: '🎷',
    color: '#D97706',
    level: 'gold',
    active: false,
  },
  {
    id: 'pk5',
    partnerId: 'c1',
    partnerName: 'Boulangerie du Marché',
    offer: 'Viennoiserie offerte le matin',
    icon: '🥐',
    color: '#B45309',
    level: 'basic',
    active: true,
  },
  {
    id: 'pk6',
    partnerId: 'f3',
    partnerName: 'Marie Design',
    offer: 'Audit identité visuelle offert',
    icon: '🎨',
    color: '#7C3AED',
    level: 'business',
    active: false,
  },
] as const;

export type MockPerk = (typeof MOCK_PERKS)[number];
