import type { ProfileKind } from '@/constants/mockProfiles';

export type FeedPostType = 'offer' | 'event' | 'question' | 'text';

export type FeedPost = {
  id: string;
  authorId: string;
  authorName: string;
  authorType: ProfileKind;
  content: string;
  type: FeedPostType;
  likes: number;
  comments: number;
  shares: number;
  timestamp: string;
  hasImage: boolean;
  imageColor: string;
  imageEmoji?: string;
  /** Filtrage tribu (mock) */
  tribeId?: string;
};

export const MOCK_POSTS: FeedPost[] = [
  {
    id: 'p1',
    authorId: 'c2',
    authorName: 'Belga Queen',
    authorType: 'commercial',
    content: 'Happy hour ce vendredi 18h ! 2 boissons = 1 offerte 🍺 Venez nombreux !',
    type: 'offer',
    likes: 47,
    comments: 12,
    shares: 8,
    timestamp: '2min',
    hasImage: true,
    imageColor: '#16A34A',
    imageEmoji: '🍺',
    tribeId: 't4',
  },
  {
    id: 'p2',
    authorId: 'u1',
    authorName: 'Léa Martin',
    authorType: 'yunicitizen',
    content: "Quelqu'un connaît un bon réparateur vélo dans le centre ? Mon dérailleur est HS 🚲",
    type: 'question',
    likes: 8,
    comments: 23,
    shares: 2,
    timestamp: '15min',
    hasImage: false,
    imageColor: '#2A2FFF',
    tribeId: 't1',
  },
  {
    id: 'p3',
    authorId: 'a1',
    authorName: 'Jazz au Parvis',
    authorType: 'association',
    content:
      'Concert gratuit samedi au Parvis de la Cathédrale 🎷 Jazz manouche avec le Quartet Duplessis. 20h30, entrée libre !',
    type: 'event',
    likes: 89,
    comments: 34,
    shares: 56,
    timestamp: '1h',
    hasImage: true,
    imageColor: '#D97706',
    imageEmoji: '🎷',
    tribeId: 't2',
  },
  {
    id: 'p4',
    authorId: 'c1',
    authorName: 'Boulangerie du Marché',
    authorType: 'commercial',
    content: 'Notre pain au levain est enfourné chaque matin à 4h. Venez découvrir nos nouvelles viennoiseries au beurre AOP 🥐',
    type: 'text',
    likes: 124,
    comments: 18,
    shares: 11,
    timestamp: '2h',
    hasImage: true,
    imageColor: '#B45309',
    imageEmoji: '🥐',
  },
  {
    id: 'p5',
    authorId: 'u3',
    authorName: 'Emma Petit',
    authorType: 'yunicitizen',
    content: 'Photos de la fête de quartier Croix-Rouge hier soir 📸 Quelle ambiance ! Merci à tous les bénévoles',
    type: 'text',
    likes: 203,
    comments: 45,
    shares: 28,
    timestamp: '3h',
    hasImage: true,
    imageColor: '#2A2FFF',
    imageEmoji: '📸',
    tribeId: 't1',
  },
  {
    id: 'p6',
    authorId: 'a2',
    authorName: 'Cyclistes de Reims',
    authorType: 'association',
    content: "Balade vélo ce dimanche matin ! Départ Place d'Erlon à 9h. Toutes les vitesses bienvenues 🚴‍♀️ Distance : 25km",
    type: 'event',
    likes: 67,
    comments: 19,
    shares: 34,
    timestamp: '5h',
    hasImage: false,
    imageColor: '#16A34A',
    tribeId: 't1',
  },
  {
    id: 'p7',
    authorId: 'f3',
    authorName: 'Marie Design',
    authorType: 'freelance',
    content: 'Je recherche des commerçants rémois pour une refonte de leur identité visuelle. Tarifs adaptés aux TPE 🎨',
    type: 'offer',
    likes: 15,
    comments: 7,
    shares: 4,
    timestamp: '6h',
    hasImage: true,
    imageColor: '#7C3AED',
    imageEmoji: '🎨',
    tribeId: 't4',
  },
  {
    id: 'p8',
    authorId: 'u5',
    authorName: 'Sarah Cohen',
    authorType: 'yunicitizen',
    content: 'Saviez-vous que Reims compte 47 jardins partagés ? On peut encore en créer dans le quartier Croix-Rouge ! 🌱',
    type: 'text',
    likes: 38,
    comments: 14,
    shares: 22,
    timestamp: '8h',
    hasImage: false,
    imageColor: '#16A34A',
  },
  {
    id: 'p9',
    authorId: 'c4',
    authorName: 'Ao Barber',
    authorType: 'commercial',
    content: 'Nouveau soin disponible : massage californien 60min à 55€ au lieu de 75€ pour les porteurs du Pass Yunicity 💆',
    type: 'offer',
    likes: 56,
    comments: 8,
    shares: 15,
    timestamp: '10h',
    hasImage: true,
    imageColor: '#0891B2',
    imageEmoji: '💆',
  },
  {
    id: 'p10',
    authorId: 'e1',
    authorName: 'École des Arts de Reims',
    authorType: 'ecole',
    content: 'Portes ouvertes le 15 mai ! Venez découvrir nos formations en arts plastiques, design et photographie 🎭',
    type: 'event',
    likes: 44,
    comments: 11,
    shares: 19,
    timestamp: '12h',
    hasImage: true,
    imageColor: '#DC2626',
    imageEmoji: '🎭',
  },
  {
    id: 'p11',
    authorId: 'c5',
    authorName: 'Cave des Sacres',
    authorType: 'commercial',
    content: 'Dégustation champagnes de vignerons indépendants samedi 17h — 12 places seulement 🍾',
    type: 'event',
    likes: 72,
    comments: 21,
    shares: 9,
    timestamp: '14h',
    hasImage: true,
    imageColor: '#7C3AED',
    imageEmoji: '🍾',
    tribeId: 't5',
  },
  {
    id: 'p12',
    authorId: 'u2',
    authorName: 'Thomas Dubois',
    authorType: 'yunicitizen',
    content: 'Le quartet du Parvis hier soir : niveau international. Bravo aux bénévoles de Jazz au Parvis 👏',
    type: 'text',
    likes: 31,
    comments: 6,
    shares: 3,
    timestamp: '16h',
    hasImage: false,
    imageColor: '#D97706',
    tribeId: 't2',
  },
  {
    id: 'p13',
    authorId: 'c6',
    authorName: 'Yoga Reims',
    authorType: 'commercial',
    content: 'Cours en plein air dimanche 10h — parc de la Patte d’Oie. Tapis fournis sur inscription 🧘',
    type: 'offer',
    likes: 41,
    comments: 9,
    shares: 12,
    timestamp: '18h',
    hasImage: true,
    imageColor: '#D97706',
    imageEmoji: '🧘',
    tribeId: 't1',
  },
  {
    id: 'p14',
    authorId: 'f1',
    authorName: 'Studio Photo Rémois',
    authorType: 'freelance',
    content: 'Mini-séances portraits pro à 39€ ce week-end — booker en DM 📷',
    type: 'offer',
    likes: 28,
    comments: 14,
    shares: 7,
    timestamp: '20h',
    hasImage: true,
    imageColor: '#2A2FFF',
    imageEmoji: '📷',
    tribeId: 't6',
  },
  {
    id: 'p15',
    authorId: 'a3',
    authorName: 'Repair Café Reims',
    authorType: 'association',
    content: 'Atelier ce samedi : réparer petit électroménager. Apportez vos apparels ! 🔧',
    type: 'event',
    likes: 54,
    comments: 17,
    shares: 22,
    timestamp: '1j',
    hasImage: false,
    imageColor: '#D97706',
    tribeId: 't3',
  },
  {
    id: 'p16',
    authorId: 'c7',
    authorName: 'Bio Market',
    authorType: 'commercial',
    content: 'Arrivage tomates anciennes + courgettes jaunes — producteurs à moins de 40 km 🍅',
    type: 'text',
    likes: 63,
    comments: 5,
    shares: 8,
    timestamp: '1j',
    hasImage: true,
    imageColor: '#16A34A',
    imageEmoji: '🍅',
  },
  {
    id: 'p17',
    authorId: 'f2',
    authorName: 'Dev & Co',
    authorType: 'freelance',
    content: 'On recrute un·e dev React Native pour une app locale (6 mois). Remote friendly 💻',
    type: 'question',
    likes: 19,
    comments: 41,
    shares: 6,
    timestamp: '2j',
    hasImage: false,
    imageColor: '#7C3AED',
    tribeId: 't7',
  },
  {
    id: 'p18',
    authorId: 'e2',
    authorName: 'CFA Reims',
    authorType: 'ecole',
    content: 'Inscriptions alternance commerce jusqu’au 30 avril — infos sur place ou en ligne 📋',
    type: 'text',
    likes: 22,
    comments: 3,
    shares: 11,
    timestamp: '2j',
    hasImage: false,
    imageColor: '#DC2626',
  },
  {
    id: 'p19',
    authorId: 'u4',
    authorName: 'Lucas Bernard',
    authorType: 'yunicitizen',
    content: 'Première sortie avec le groupe Cyclistes de Reims — accueil au top ! Merci 🚴',
    type: 'text',
    likes: 14,
    comments: 4,
    shares: 1,
    timestamp: '3j',
    hasImage: true,
    imageColor: '#16A34A',
    imageEmoji: '🚴',
    tribeId: 't1',
  },
  {
    id: 'p20',
    authorId: 'c8',
    authorName: 'Studio 51',
    authorType: 'commercial',
    content: 'Making-of du clip des associations rémoises — sortie vendredi minuit 🎬',
    type: 'event',
    likes: 91,
    comments: 28,
    shares: 44,
    timestamp: '3j',
    hasImage: true,
    imageColor: '#0D0F2E',
    imageEmoji: '🎬',
    tribeId: 't6',
  },
];

export function postsForTribe(tribeId: string): FeedPost[] {
  const tagged = MOCK_POSTS.filter((p) => p.tribeId === tribeId);
  if (tagged.length) return tagged;
  return MOCK_POSTS.slice(0, 8);
}
