import type { ProfileKind } from '@/constants/mockProfiles';

export type FeedPostType = 'offer' | 'event' | 'question' | 'text';

export type FeedPost = {
  id: string;
  authorId: string;
  authorName: string;
  authorType: ProfileKind;
  content: string;
  type: FeedPostType;
  likes: number;
  comments: number;
  shares: number;
  timestamp: string;
  hasImage: boolean;
  hasVideo?: boolean;
  imageColor: string;
  imageEmoji?: string;
  /** Image distante (ex. Unsplash) — prioritaire sur le bloc emoji si défini */
  imageUrl?: string;
  thumbnailUrl?: string;
  videoUrl?: string;
  /** Filtrage tribu (mock) */
  tribeId?: string;
};

export const MOCK_POSTS: FeedPost[] = [
  // Publications "profil" (yunicitizen) — images pour remplir la grille
  {
    id: 'u1p1',
    authorId: 'u1',
    authorName: 'Kyria',
    authorType: 'yunicitizen',
    content: 'Balade au coucher de soleil vers la Cathédrale. Reims est magique 🌇',
    type: 'text',
    likes: 182,
    comments: 21,
    shares: 9,
    timestamp: '5 min',
    hasImage: true,
    imageColor: '#2A2FFF',
    imageEmoji: '🌇',
    imageUrl: 'https://images.pexels.com/photos/1366919/pexels-photo-1366919.jpeg?w=800',
    tribeId: 't1',
  },
  {
    id: 'u1p2',
    authorId: 'u1',
    authorName: 'Kyria',
    authorType: 'yunicitizen',
    content: 'Petit café du matin + carnet de notes = bonne journée ☕',
    type: 'text',
    likes: 96,
    comments: 8,
    shares: 2,
    timestamp: '20 min',
    hasImage: true,
    imageColor: '#B45309',
    imageEmoji: '☕',
    imageUrl: 'https://images.pexels.com/photos/302899/pexels-photo-302899.jpeg?w=800',
    tribeId: 't1',
  },
  {
    id: 'u1p3',
    authorId: 'u1',
    authorName: 'Kyria',
    authorType: 'yunicitizen',
    content: "Marché du matin : légumes locaux et fleurs fraîches 🌼",
    type: 'text',
    likes: 141,
    comments: 12,
    shares: 6,
    timestamp: '1h',
    hasImage: true,
    imageColor: '#16A34A',
    imageEmoji: '🌼',
    imageUrl: 'https://images.pexels.com/photos/3962285/pexels-photo-3962285.jpeg?w=800',
    tribeId: 't1',
  },
  {
    id: 'u1p4',
    authorId: 'u1',
    authorName: 'Kyria',
    authorType: 'yunicitizen',
    content: 'Session photo improvisée dans les rues du centre 📷',
    type: 'text',
    likes: 210,
    comments: 29,
    shares: 14,
    timestamp: '3h',
    hasImage: true,
    imageColor: '#2A2FFF',
    imageEmoji: '📷',
    imageUrl: 'https://images.pexels.com/photos/212372/pexels-photo-212372.jpeg?w=800',
    tribeId: 't6',
  },
  {
    id: 'u1p5',
    authorId: 'u1',
    authorName: 'Kyria',
    authorType: 'yunicitizen',
    content: 'Spot préféré pour lire au calme : parc de la Patte d’Oie 📚',
    type: 'text',
    likes: 77,
    comments: 6,
    shares: 1,
    timestamp: '6h',
    hasImage: true,
    imageColor: '#16A34A',
    imageEmoji: '📚',
    imageUrl: 'https://images.pexels.com/photos/1029141/pexels-photo-1029141.jpeg?w=800',
    tribeId: 't1',
  },
  {
    id: 'u1p6',
    authorId: 'u1',
    authorName: 'Kyria',
    authorType: 'yunicitizen',
    content: "Détail d’architecture : ces façades sont incroyables 🤍",
    type: 'text',
    likes: 129,
    comments: 10,
    shares: 4,
    timestamp: '1j',
    hasImage: true,
    imageColor: '#0D0F2E',
    imageEmoji: '🏛️',
    imageUrl: 'https://images.pexels.com/photos/208701/pexels-photo-208701.jpeg?w=800',
  },
  {
    id: 'u1p7',
    authorId: 'u1',
    authorName: 'Kyria',
    authorType: 'yunicitizen',
    content: 'Brunch entre amis ce week-end, à refaire ! 🥞',
    type: 'text',
    likes: 164,
    comments: 18,
    shares: 7,
    timestamp: '2j',
    hasImage: true,
    imageColor: '#D97706',
    imageEmoji: '🥞',
    imageUrl: 'https://images.pexels.com/photos/376464/pexels-photo-376464.jpeg?w=800',
  },
  {
    id: 'u1p8',
    authorId: 'u1',
    authorName: 'Kyria',
    authorType: 'yunicitizen',
    content: 'Balade à vélo et grand air. Merci Reims 🚴‍♀️',
    type: 'text',
    likes: 112,
    comments: 9,
    shares: 3,
    timestamp: '4j',
    hasImage: true,
    imageColor: '#16A34A',
    imageEmoji: '🚴‍♀️',
    imageUrl: 'https://images.pexels.com/photos/276517/pexels-photo-276517.jpeg?w=800',
    tribeId: 't1',
  },
  {
    id: 'pv1',
    authorId: 'a1',
    authorName: 'Jazz au Parvis',
    authorType: 'association',
    content: 'Ambiance du dernier concert Jazz au Parvis 🎷',
    type: 'event',
    likes: 156,
    comments: 43,
    shares: 67,
    timestamp: '30 min',
    hasImage: false,
    hasVideo: true,
    imageColor: '#D97706',
    thumbnailUrl: 'https://images.pexels.com/videos/2795405/free-video-2795405.jpg?w=800',
    videoUrl: 'https://www.pexels.com/video/2795405/download/',
    tribeId: 't2',
  },
  {
    id: 'p1',
    authorId: 'c2',
    authorName: 'Belga Queen',
    authorType: 'commercial',
    content: 'Happy hour ce vendredi 18h ! 2 boissons = 1 offerte 🍺 Venez nombreux !',
    type: 'offer',
    likes: 47,
    comments: 12,
    shares: 8,
    timestamp: '2 min',
    hasImage: true,
    imageColor: '#16A34A',
    imageEmoji: '🍺',
    imageUrl: 'https://images.pexels.com/photos/1267360/pexels-photo-1267360.jpeg?w=800',
    tribeId: 't4',
  },
  {
    id: 'p2',
    authorId: 'u1',
    authorName: 'Kyria',
    authorType: 'yunicitizen',
    content: "Quelqu'un connaît un bon réparateur vélo dans le centre ? Mon dérailleur est HS 🚲",
    type: 'question',
    likes: 8,
    comments: 23,
    shares: 2,
    timestamp: '15 min',
    hasImage: false,
    imageColor: '#2A2FFF',
    tribeId: 't1',
  },
  {
    id: 'p3',
    authorId: 'a1',
    authorName: 'Jazz au Parvis',
    authorType: 'association',
    content:
      'Concert gratuit samedi au Parvis de la Cathédrale 🎷 Jazz manouche avec le Quartet Duplessis. 20h30, entrée libre !',
    type: 'event',
    likes: 89,
    comments: 34,
    shares: 56,
    timestamp: '1h',
    hasImage: true,
    imageColor: '#D97706',
    imageEmoji: '🎷',
    imageUrl: 'https://images.pexels.com/photos/1190297/pexels-photo-1190297.jpeg?w=800',
    tribeId: 't2',
  },
  {
    id: 'p4',
    authorId: 'c1',
    authorName: 'Boulangerie du Marché',
    authorType: 'commercial',
    content: 'Notre pain au levain est enfourné chaque matin à 4h. Venez découvrir nos nouvelles viennoiseries au beurre AOP 🥐',
    type: 'text',
    likes: 124,
    comments: 18,
    shares: 11,
    timestamp: '2h',
    hasImage: true,
    imageColor: '#B45309',
    imageEmoji: '🥐',
    imageUrl: 'https://images.pexels.com/photos/1126359/pexels-photo-1126359.jpeg?w=800',
  },
  {
    id: 'p5',
    authorId: 'u3',
    authorName: 'Emma Petit',
    authorType: 'yunicitizen',
    content: 'Photos de la fête de quartier Croix-Rouge hier soir 📸 Quelle ambiance ! Merci à tous les bénévoles',
    type: 'text',
    likes: 203,
    comments: 45,
    shares: 28,
    timestamp: '3h',
    hasImage: true,
    imageColor: '#2A2FFF',
    imageEmoji: '📸',
    imageUrl: 'https://images.pexels.com/photos/2263436/pexels-photo-2263436.jpeg?w=800',
    tribeId: 't1',
  },
  {
    id: 'p6',
    authorId: 'a2',
    authorName: 'Cyclistes de Reims',
    authorType: 'association',
    content: "Balade vélo ce dimanche matin ! Départ Place d'Erlon à 9h. Toutes les vitesses bienvenues 🚴‍♀️ Distance : 25km",
    type: 'event',
    likes: 67,
    comments: 19,
    shares: 34,
    timestamp: '5h',
    hasImage: false,
    imageColor: '#16A34A',
    tribeId: 't1',
  },
  {
    id: 'p7',
    authorId: 'f3',
    authorName: 'Marie Design',
    authorType: 'freelance',
    content: 'Je recherche des commerçants rémois pour une refonte de leur identité visuelle. Tarifs adaptés aux TPE 🎨',
    type: 'offer',
    likes: 15,
    comments: 7,
    shares: 4,
    timestamp: '6h',
    hasImage: true,
    imageColor: '#7C3AED',
    imageEmoji: '🎨',
    imageUrl: 'https://images.pexels.com/photos/196644/pexels-photo-196644.jpeg?w=800',
    tribeId: 't4',
  },
  {
    id: 'p8',
    authorId: 'u5',
    authorName: 'Sarah Cohen',
    authorType: 'yunicitizen',
    content: 'Saviez-vous que Reims compte 47 jardins partagés ? On peut encore en créer dans le quartier Croix-Rouge ! 🌱',
    type: 'text',
    likes: 38,
    comments: 14,
    shares: 22,
    timestamp: '8h',
    hasImage: false,
    imageColor: '#16A34A',
  },
  {
    id: 'p9',
    authorId: 'c4',
    authorName: 'Ao Barber',
    authorType: 'commercial',
    content: 'Nouveau soin disponible : massage californien 60min à 55€ au lieu de 75€ pour les porteurs du Pass Yunicity 💆',
    type: 'offer',
    likes: 56,
    comments: 8,
    shares: 15,
    timestamp: '10h',
    hasImage: true,
    imageColor: '#0891B2',
    imageEmoji: '💆',
    imageUrl: 'https://images.pexels.com/photos/3757942/pexels-photo-3757942.jpeg?w=800',
  },
  {
    id: 'p10',
    authorId: 'e1',
    authorName: 'École des Arts de Reims',
    authorType: 'ecole',
    content: 'Portes ouvertes le 15 mai ! Venez découvrir nos formations en arts plastiques, design et photographie 🎭',
    type: 'event',
    likes: 44,
    comments: 11,
    shares: 19,
    timestamp: '12h',
    hasImage: true,
    imageColor: '#DC2626',
    imageEmoji: '🎭',
    imageUrl: 'https://images.pexels.com/photos/1266808/pexels-photo-1266808.jpeg?w=800',
  },
  {
    id: 'p11',
    authorId: 'c5',
    authorName: 'Cave des Sacres',
    authorType: 'commercial',
    content: 'Dégustation champagnes de vignerons indépendants samedi 17h — 12 places seulement 🍾',
    type: 'event',
    likes: 72,
    comments: 21,
    shares: 9,
    timestamp: '14h',
    hasImage: true,
    imageColor: '#7C3AED',
    imageEmoji: '🍾',
    imageUrl: 'https://images.pexels.com/photos/1283219/pexels-photo-1283219.jpeg?w=800',
    tribeId: 't5',
  },
  {
    id: 'p12',
    authorId: 'u2',
    authorName: 'Thomas Dubois',
    authorType: 'yunicitizen',
    content: 'Le quartet du Parvis hier soir : niveau international. Bravo aux bénévoles de Jazz au Parvis 👏',
    type: 'text',
    likes: 31,
    comments: 6,
    shares: 3,
    timestamp: '16h',
    hasImage: false,
    imageColor: '#D97706',
    tribeId: 't2',
  },
  {
    id: 'p13',
    authorId: 'c6',
    authorName: 'Yoga Reims',
    authorType: 'commercial',
    content: 'Cours en plein air dimanche 10h — parc de la Patte d’Oie. Tapis fournis sur inscription 🧘',
    type: 'offer',
    likes: 41,
    comments: 9,
    shares: 12,
    timestamp: '18h',
    hasImage: true,
    imageColor: '#D97706',
    imageEmoji: '🧘',
    imageUrl: 'https://images.pexels.com/photos/3823039/pexels-photo-3823039.jpeg?w=800',
    tribeId: 't1',
  },
  {
    id: 'p14',
    authorId: 'f1',
    authorName: 'Studio Photo Rémois',
    authorType: 'freelance',
    content: 'Mini-séances portraits pro à 39€ ce week-end — booker en DM 📷',
    type: 'offer',
    likes: 28,
    comments: 14,
    shares: 7,
    timestamp: '20h',
    hasImage: true,
    imageColor: '#2A2FFF',
    imageEmoji: '📷',
    imageUrl: 'https://images.pexels.com/photos/1704488/pexels-photo-1704488.jpeg?w=800',
    tribeId: 't6',
  },
  {
    id: 'p15',
    authorId: 'a3',
    authorName: 'Repair Café Reims',
    authorType: 'association',
    content: 'Atelier ce samedi : réparer petit électroménager. Apportez vos apparels ! 🔧',
    type: 'event',
    likes: 54,
    comments: 17,
    shares: 22,
    timestamp: '1j',
    hasImage: false,
    imageColor: '#D97706',
    tribeId: 't3',
  },
  {
    id: 'p16',
    authorId: 'c7',
    authorName: 'Bio Market',
    authorType: 'commercial',
    content: 'Arrivage tomates anciennes + courgettes jaunes — producteurs à moins de 40 km 🍅',
    type: 'text',
    likes: 63,
    comments: 5,
    shares: 8,
    timestamp: '1j',
    hasImage: true,
    imageColor: '#16A34A',
    imageEmoji: '🍅',
    imageUrl: 'https://images.pexels.com/photos/264537/pexels-photo-264537.jpeg?w=800',
  },
  {
    id: 'p17',
    authorId: 'f2',
    authorName: 'Dev & Co',
    authorType: 'freelance',
    content: 'On recrute un·e dev React Native pour une app locale (6 mois). Remote friendly 💻',
    type: 'question',
    likes: 19,
    comments: 41,
    shares: 6,
    timestamp: '2j',
    hasImage: false,
    imageColor: '#7C3AED',
    tribeId: 't7',
  },
  {
    id: 'p18',
    authorId: 'e2',
    authorName: 'CFA Reims',
    authorType: 'ecole',
    content: 'Inscriptions alternance commerce jusqu’au 30 avril — infos sur place ou en ligne 📋',
    type: 'text',
    likes: 22,
    comments: 3,
    shares: 11,
    timestamp: '2j',
    hasImage: false,
    imageColor: '#DC2626',
  },
  {
    id: 'p19',
    authorId: 'u4',
    authorName: 'Lucas Bernard',
    authorType: 'yunicitizen',
    content: 'Première sortie avec le groupe Cyclistes de Reims — accueil au top ! Merci 🚴',
    type: 'text',
    likes: 14,
    comments: 4,
    shares: 1,
    timestamp: '3j',
    hasImage: true,
    imageColor: '#16A34A',
    imageEmoji: '🚴',
    imageUrl: 'https://images.pexels.com/photos/276517/pexels-photo-276517.jpeg?w=800',
    tribeId: 't1',
  },
  {
    id: 'p20',
    authorId: 'c8',
    authorName: 'Studio 51',
    authorType: 'commercial',
    content: 'Making-of du clip des associations rémoises — sortie vendredi minuit 🎬',
    type: 'event',
    likes: 91,
    comments: 28,
    shares: 44,
    timestamp: '3j',
    hasImage: true,
    imageColor: '#0D0F2E',
    imageEmoji: '🎬',
    imageUrl: 'https://images.pexels.com/photos/799137/pexels-photo-799137.jpeg?w=800',
    tribeId: 't6',
  },
];

export function postsForTribe(tribeId: string): FeedPost[] {
  const tagged = MOCK_POSTS.filter((p) => p.tribeId === tribeId);
  if (tagged.length) return tagged;
  return MOCK_POSTS.slice(0, 8);
}
